baseURL = "https://huangjinbolab.github.io/"
languageCode = "zh-cn"
title = "黄金波实验室"
theme = "cai-lab"
[pagination]
  pagerSize = 10

[params]
  lab_name = "黄金波实验室（Huang Lab）@ HIM, CAS"
  tagline = "合成生物学 · 智能细胞工程 · 精准医疗"
  email = "huangjinbolab@outlook.com"
  address = "中国科学院杭州医学研究所"
  footer_text = "© 2025 黄金波实验室"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "研究内容"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "课题组长"
    url = "/team/"
    weight = 3
  [[menu.main]]
    name = "团队成员"
    url = "/team-members/"
    identifier = "team-members"
    weight = 4
  [[menu.main]]
    name = "工作人员"
    url = "/team-members/staff/"
    parent = "team-members"
    weight = 1
  [[menu.main]]
    name = "博士后"
    url = "/team-members/postdocs/"
    parent = "team-members"
    weight = 2
  [[menu.main]]
    name = "研究生"
    url = "/team-members/graduate-students/"
    parent = "team-members"
    weight = 3
  [[menu.main]]
    name = "其他成员"
    url = "/team-members/other-members/"
    parent = "team-members"
    weight = 4
  [[menu.main]]
    name = "Alumni"
    url = "/team-members/alumni/"
    parent = "team-members"
    weight = 5
  [[menu.main]]
    name = "研究成果"
    url = "/publications/"
    weight = 5
  [[menu.main]]
    name = "新闻"
    url = "/news/"
    weight = 6
  [[menu.main]]
    name = "加入我们"
    url = "/jobs/"
    weight = 7
  [[menu.main]]
    name = "实验室活动"
    url = "/misc/"
    weight = 8
